name: Export Artifacts
on: [push]

jobs:
  kicad_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the action to push the commit back
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export PDF
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_sch: hardware/emf_beacon.kicad_sch
          sch_pdf: true
      
      - name: Generate 3D STEP
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_pcb: hardware/emf_beacon.kicad_pcb
          pcb_model: true
      
      - name: Render PCB Image
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_pcb: hardware/emf_beacon.kicad_pcb
          pcb_image: true

      - name: Organize and Commit PDF
        run: |
          mkdir -p docs
          mv hardware/sch.pdf docs/emf_beacon_schematic.pdf
          mv hardware/pcb.step docs/emf_beacon_3d.step
          mv images/top.png docs/emf_beacon_top_img.png
          mv images/bottom.png docs/emf_beacon_bot_img.png
          
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          # Stage and push the changes
          git add docs/*
          git commit -m "docs: auto-generate schematic PDF, 3D model, and rear render" || echo "No changes to commit"
          git push
